-- IMS MVP core schema. UUID PKs generated by the application.

create table institute (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    name          varchar(255) not null,
    code          varchar(64)  not null unique,
    address       varchar(255),
    phone         varchar(255),
    email         varchar(255),
    logo_url      varchar(255),
    settings      text,
    status        varchar(16)  not null
);

create table app_user (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    full_name     varchar(255) not null,
    role          varchar(32)  not null,
    status        varchar(16)  not null,
    institute_id  uuid,
    profile_id    uuid,
    constraint fk_user_institute foreign key (institute_id) references institute (id)
);

create table academic_year (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid        not null,
    name          varchar(64) not null,
    start_date    date,
    end_date      date,
    is_current    boolean     not null,
    constraint fk_year_institute foreign key (institute_id) references institute (id),
    constraint uq_year_institute_name unique (institute_id, name)
);

create table grade (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid        not null,
    name          varchar(64) not null,
    order_no      integer     not null,
    constraint fk_grade_institute foreign key (institute_id) references institute (id),
    constraint uq_grade_institute_name unique (institute_id, name)
);

create table section (
    id               uuid primary key,
    created_at       timestamptz,
    updated_at       timestamptz,
    created_by       uuid,
    updated_by       uuid,
    version          bigint,
    institute_id     uuid        not null,
    grade_id         uuid        not null,
    name             varchar(64) not null,
    class_teacher_id uuid,
    capacity         integer     not null,
    constraint fk_section_institute foreign key (institute_id) references institute (id),
    constraint fk_section_grade foreign key (grade_id) references grade (id),
    constraint uq_section unique (institute_id, grade_id, name)
);

create table student (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid         not null,
    full_name     varchar(255) not null,
    reg_no        varchar(64),
    roll_no       varchar(64),
    dob           date,
    gender        varchar(16),
    photo_url     varchar(255),
    phone         varchar(255),
    email         varchar(255),
    address       varchar(255),
    status        varchar(16)  not null,
    constraint fk_student_institute foreign key (institute_id) references institute (id),
    constraint uq_student_reg unique (institute_id, reg_no)
);

create table teacher (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid         not null,
    full_name     varchar(255) not null,
    dob           date,
    gender        varchar(16),
    designation   varchar(24)  not null,
    phone         varchar(255),
    email         varchar(255),
    address       varchar(255),
    join_date     date,
    status        varchar(16)  not null,
    constraint fk_teacher_institute foreign key (institute_id) references institute (id)
);

create table guardian (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid         not null,
    full_name     varchar(255) not null,
    phone         varchar(255),
    email         varchar(255),
    occupation    varchar(255),
    address       varchar(255),
    constraint fk_guardian_institute foreign key (institute_id) references institute (id)
);

create table student_guardian (
    id            uuid primary key,
    created_at    timestamptz,
    updated_at    timestamptz,
    created_by    uuid,
    updated_by    uuid,
    version       bigint,
    institute_id  uuid        not null,
    student_id    uuid        not null,
    guardian_id   uuid        not null,
    relation      varchar(16) not null,
    is_primary    boolean     not null,
    constraint fk_sg_institute foreign key (institute_id) references institute (id),
    constraint fk_sg_student foreign key (student_id) references student (id),
    constraint fk_sg_guardian foreign key (guardian_id) references guardian (id),
    constraint uq_sg unique (student_id, guardian_id)
);

create table admission (
    id               uuid primary key,
    created_at       timestamptz,
    updated_at       timestamptz,
    created_by       uuid,
    updated_by       uuid,
    version          bigint,
    institute_id     uuid        not null,
    student_id       uuid        not null,
    academic_year_id uuid        not null,
    grade_id         uuid        not null,
    section_id       uuid,
    admission_no     varchar(64),
    admission_date   date,
    status           varchar(16) not null,
    constraint fk_adm_institute foreign key (institute_id) references institute (id),
    constraint fk_adm_student foreign key (student_id) references student (id),
    constraint fk_adm_year foreign key (academic_year_id) references academic_year (id),
    constraint fk_adm_grade foreign key (grade_id) references grade (id),
    constraint fk_adm_section foreign key (section_id) references section (id),
    constraint uq_adm_no unique (institute_id, admission_no)
);

create index idx_academic_year_institute on academic_year (institute_id);
create index idx_grade_institute on grade (institute_id);
create index idx_section_institute on section (institute_id);
create index idx_student_institute on student (institute_id);
create index idx_teacher_institute on teacher (institute_id);
create index idx_guardian_institute on guardian (institute_id);
create index idx_student_guardian_institute on student_guardian (institute_id);
create index idx_admission_institute on admission (institute_id);
